### ISSUE TITLE
add repeat-text attr ~ feedback

### ISSUE THREAD

**Issue by NotableAPP** [Auroratide/typewritten-text#1]
# ***FEEDBACK***
Hey there,
Add new `repeat-text` attribute
## *Update*
The repeat-text attr can be a string or array
```html
<tag repeat-text="my second text , my third text" repeat>my first text</tag>
```
## output
The output should be like
- `my first text` will written first then `my second text` , `my third text` 
- if the `repeat` attribute is true , this output will work in loop.

Thank you,
Shubham

**Comment by Auroratide** [comment]
Thanks for the suggestion!

I had actually thought about this before and in the end decided against adding auto-rotation so that the element would be as unopinionated as feasible, allowing it to be used in a wider variety of use cases.

As a result, even though the feature is not built-in, it is possible to use its interface to implement it. I actually knew this was a common case, so I built out a **[Codepen Demonstration](https://codepen.io/auroratide/pen/BaZWWwQ)** showing how to accomplish it.

The relevant code:

```html
<ul class="typewriter-cycle">
  <li><typewritten-text>my first text</typewritten-text></li>
  <li><typewritten-text paused>my second text</typewritten-text></li>
  <li><typewritten-text paused>my third text</typewritten-text></li>
</ul>
```

```js
document.querySelectorAll('.typewriter-cycle').forEach(cycle => {
  const items = cycle.querySelectorAll('typewritten-text')
  for (let i = 0; i < items.length; ++i) {
    const cur = items[i]
    const next = items[i === items.length - 1 ? 0 : i + 1]
    
    cur.addEventListener('typewritten-text:phrasetyped', () => setTimeout(cur.start, cur.phraseInterval))
    cur.addEventListener('typewritten-text:phraseremoved', () => {
      cur.classList.remove('active')
      next.classList.add('active')
      setTimeout(next.start, next.phraseInterval)
    })
  }
})
```

The advantage is now `my second text` and `my third text` can use HTML tags as well.

**Comment by NotableAPP** [comment]
I would like it if the attribute or any built-in solution arrive in next version
Thanks,
Shubham
